version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 0

    - package-ecosystem: "docker"
      directory: "/streaming/kafka"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 0

    - package-ecosystem: "docker"
      directory: "/clustering/kubernetes/mmr/agmmr"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 0

    - package-ecosystem: "docker"
      directory: "/spark/.docker"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 0
