#
# stateful set of controlling instance
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-controlling
spec:
  # rwy: selector added
  selector:
    matchLabels:
#      # has to match .spec.template.metadata.labels
      app: {{ .Release.Name }}-controlling
  serviceName: {{ .Release.Name }}-controlling
  replicas: 1
  #
  # Update Strategy
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-controlling
    spec:
        containers:
        - name: {{ .Release.Name }}-controlling
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # CPU limits for the Horizontal Pod Autoscaler, HPA
          resources:
            limits:
              cpu: {{ .Values.cpu.limit}}
            requests:
              cpu: {{ .Values.cpu.request}}
          livenessProbe:
            httpGet:
              path: /version
              port: {{ .Values.port }}
            initialDelaySeconds: 30
          volumeMounts:
          - name: shm
            mountPath: /dev/shm
          - name: {{ .Release.Name }}-data
            mountPath: /app/rootcatalog
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
          env:
          - name: Controlling
            value: "yes"
          - name: ControllingHost
            value: "{{ .Release.Name }}-controlling"
        volumes:
        - name: shm
          emptyDir:
             medium: Memory
        - name: secrets
          secret:
             secretName: {{ .Release.Name }}-agraphsecrets
  volumeClaimTemplates:
         - metadata:
            name: {{ .Release.Name }}-data
           spec:
            resources:
              requests:
                storage: {{ .Values.dataStorage }}
            accessModes:
            - ReadWriteOnce