FROM postgres:13
LABEL maintainer="Tianyu Gu <gty@franz.com>"

WORKDIR /tmp

RUN apt-get -qq update -y && apt-get upgrade -y && \
    apt-get install -y curl zip unzip

ARG demo_size=small
RUN curl -L https://edu.postgrespro.com/demo-${demo_size}-en.zip > demo-${demo_size}-en.zip && \
    unzip demo-${demo_size}-en.zip && rm demo-${demo_size}-en.zip

COPY bin/init-db.sh /docker-entrypoint-initdb.d/
RUN chmod a+x /docker-entrypoint-initdb.d/init-db.sh
