#
# this service exposes the internal IP address
# of the controlling instance and makes it
# available via dns at the
# name 'releasename-controlling'
# using the dns search list
#
apiVersion: v1
kind: Service
metadata:
 name: {{ .Release.Name }}-controlling
spec:
 clusterIP:  None
 selector:
   app: {{ .Release.Name }}-controlling
 ports:
 - name: http
   port: {{ .Values.port }}
   targetPort: {{ .Values.port }}
   
   
 
   
