kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-agraphsecrets
stringData:
  user: "{{ .Values.user }}"
  password: "{{ .Values.password }}"
  port: "{{ .Values.port }}"
  reponame: "{{ .Values.reponame }}"
  license: {{ .Values.license | default "" | quote }}

  
