FROM bitnami/spark:3.1.2

USER root
RUN apt-get update -y && apt-get install -y libyaml-dev
RUN python3.6 -m pip install -U pip
RUN python3.6 -m pip install --no-cache-dir scikit-learn pandas jupyterlab matplotlib requests pyyaml agraph-python

RUN mkdir /root/work
